### PR TITLE
v3.4.2 merge to master

### PR DESCRIPTION
**Pull request by TheDuckCow**
WIP merge to master. Will keep open until the final branches are merged.

Current test run:

```
blender	failed_test	short_err
(3, 5, 0)	import_mineways_combined	unmapped than mapped
(3, 5, 0)	qa_rigs	 steve_noface.png']]
(3, 4, 0)	import_mineways_combined	unmapped than mapped
(3, 4, 0)	qa_rigs	 steve_noface.png']]
(3, 2, 1)	import_mineways_combined	unmapped than mapped
(3, 2, 1)	CRASH during qa_effects	-
(3, 3, 1)	import_mineways_combined	unmapped than mapped
(3, 3, 1)	CRASH during img_sequence_effect_spawner	-
(3, 1, 0)	import_mineways_combined	unmapped than mapped
(3, 1, 0)	qa_rigs	 steve_noface.png']]
(3, 0, 0)	import_mineways_combined	unmapped than mapped
(3, 0, 0)	qa_rigs	 steve_noface.png']]
(2, 93, 0)	import_mineways_combined	unmapped than mapped
(2, 93, 0)	qa_effects	 loss of data!\n \n 
(2, 93, 0)	qa_rigs	 loss of data!\n \n 
(2, 90, 1)	import_mineways_combined	unmapped than mapped
(2, 90, 1)	qa_effects	 loss of data!\n \n 
(2, 90, 1)	qa_rigs	 loss of data!\n \n 
(2, 80, 75)	import_mineways_combined	unmapped than mapped
(2, 80, 75)	CRASH during img_sequence_effect_spawner	-
```

### CODE REVIEW

**Comment by TheDuckCow** [comment]
Latest test results with merge to silence some unnecessary mineways atlas errors:

```
blender	failed_test	short_err
(3, 5, 0)	qa_rigs	 steve_noface.png']]
(3, 4, 0)	qa_rigs	 steve_noface.png']]
(3, 2, 1)	CRASH during qa_rigs	-
(3, 3, 1)	CRASH during openfolder	-
(3, 1, 0)	qa_rigs	 steve_noface.png']]
(3, 0, 0)	qa_rigs	 steve_noface.png']]
(2, 93, 0)	qa_effects	 loss of data!\n \n 
(2, 93, 0)	qa_rigs	 loss of data!\n \n 
(2, 90, 1)	qa_effects	 loss of data!\n \n 
(2, 90, 1)	qa_rigs	 loss of data!\n \n 
(2, 80, 75)	CRASH during img_sequence_effect_spawner	-
```

The qa_rigs isn't a user facing issue, so I'm going to ignore it.
Need to do a basic UAT run and then prep the release artwork (contest winner entry!)

**Comment by StandingPadAnimations** [comment]
Very excited for the 3.4.2 release

**Comment by TheDuckCow** [comment]
Alright, live QA is yielding some problems.

- On old jmc2obj imports, Textureswap with water is resulting in some particle image being mapped in.
    -  This is due to the texture being named "water", and more recent exports name it now as `water_still` (well, rather, more literally as `minecraft_block-water_still`). Technically would only affect old world exports, but might be nice to prevent this from turning into an issue
- The still water image from jmc2obj is not being detected as grayscale, so water is coming in gray when it's coming from this `water.png` image in old exports
    - But, once again, newer exports have the saturation check going fine. Not really sure what's going on here.

**Comment by TheDuckCow** [comment]
Pushed a change which address my main concerns for now. 

```
blender	failed_test	short_err
(3, 5, 0)	qa_rigs	 steve_noface.png']]
(3, 4, 0)	qa_rigs	 steve_noface.png']]
(3, 2, 1)	CRASH during spawn_mob	-
(3, 3, 1)	CRASH during qa_meshswap_file	-
(3, 1, 0)	qa_rigs	 steve_noface.png']]
(3, 0, 0)	qa_rigs	 steve_noface.png']]
(2, 93, 0)	qa_effects	 loss of data!\n \n 
(2, 93, 0)	qa_rigs	 loss of data!\n \n 
(2, 90, 1)	qa_effects	 loss of data!\n \n 
(2, 90, 1)	qa_rigs	 loss of data!\n \n 
(2, 80, 75)	CRASH during img_sequence_effect_spawner	-
```

**Pull request merged**
